server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name jcnodex.ru www.jcnodex.ru jcnodex 192.168.102.129 88.201.150.73;

    client_max_body_size 2048m;

    access_log /var/log/nginx/jcnodex.access.log;
    error_log /var/log/nginx/jcnodex.error.log;

    location /static/ {
        alias /opt/jc-coach/app/static/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://127.0.0.1:8010;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }
}
